security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: [ROLE_VENDEDOR, ROLE_GESTORSTOCK, ROLE_USUARIO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home_page
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
                clear_site_data: 
                    - cookies
            login_throttling:
                max_attempts: 3
                interval: '1 minutes'

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/login-guest, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/product/detail, roles: [ROLE_INVITADO, ROLE_VENDEDOR, ROLE_USUARIO] }
        - { path: ^/product/list, roles: [ROLE_INVITADO, ROLE_USUARIO, ROLE_VENDEDOR] }
        - { path: ^/home/page, roles: [ROLE_USER, ROLE_GESTORSTOCK, ROLE_VENDEDOR, ROLE_INVITADO] }
        - { path: ^/product, roles: [ROLE_USUARIO, ROLE_VENDEDOR, ROLE_GESTORSTOCK, ROLE_INVITADO] }
        - { path: ^/add-used-machinery, roles: [ROLE_VENDEDOR] }
        - { path: ^/view-used-machinery, roles: [ROLE_VENDEDOR] }
        - { path: ^/product/new, roles: [ROLE_VENDEDOR, ROLE_GESTORSTOCK] }
        - { path: ^/cart, roles: [ROLE_USUARIO] }
        - { path: ^/favorite, roles: [ROLE_USUARIO] }
        - { path: ^/stock/view, roles: [ROLE_VENDEDOR, ROLE_GESTORSTOCK] }
        - { path: ^/category/new, roles: [ROLE_VENDEDOR] }
        - { path: ^/category, roles: [ROLE_VENDEDOR] }
        - { path: ^/used-machinery/detail, roles: [ROLE_VENDEDOR, ROLE_USUARIO, ROLE_INVITADO] }
        - { path: ^/usedMachinery/section, roles: [ROLE_VENDEDOR, ROLE_USUARIO, ROLE_INVITADO] }
        - { path: ^/usedMachinery/category, roles: [ROLE_VENDEDOR, ROLE_USUARIO, ROLE_INVITADO] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10